### ISSUE TITLE
Design: Web (Client)

### ISSUE THREAD

**Issue by Stier-09** [Stier-09/hwr-zeiterfassung-backend#1]
Kommen und Gehen anschauen
Kommen und Gehen ändern
Navigation

**Comment by jerdbaer** [comment]
https://hwrberlinde.sharepoint.com/:p:/r/sites/ClientServer/Freigegebene%20Dokumente/General/Design/DesignKonzept-WIP.pptx?d=wb8696a2a692d442aba3d9d366c20acdd&csf=1&web=1&e=mDn9im
