### ISSUE TITLE
Design: PC (Client)

### ISSUE THREAD

**Issue by Stier-09** [Stier-09/hwr-zeiterfassung-backend#2]
Kommen und Gehen Buttons
Pause?
weitere Buttons?

**Comment by jerdbaer** [comment]
![PC Client AZ Scenes](https://user-images.githubusercontent.com/84909173/158820691-c90b86da-6200-45b4-8d94-5e41fa97cbe0.png)

**Comment by jerdbaer** [comment]
<img width="236" alt="Bildschirmfoto 2022-03-17 um 18 59 04" src="https://user-images.githubusercontent.com/84909173/158866460-4b3b75d1-c416-43cb-80aa-910d015ac2b0.png">


oder untereinander damit das Feld kleiner ist... pause sollte noch neben Arbeitszeit stehen, damit es dann zur Webseite Matches

**Comment by jerdbaer** [comment]
<img width="753" alt="Bildschirmfoto 2022-03-17 um 19 02 39" src="https://user-images.githubusercontent.com/84909173/158866829-98852c45-98b8-49fd-8906-19fc39338e36.png">
