### ISSUE TITLE
Design: Standard Farben und Formen

### ISSUE THREAD

**Issue by Stier-09** [Stier-09/hwr-zeiterfassung-backend#3]

**Comment by jerdbaer** [comment]
Standardfarben wie in angehängter Datei

Primärfarben rot, blau, grau

![Bildschirmfoto 2022-03-13 um 13 05 42](https://user-images.githubusercontent.com/84909173/158696077-6df5a29f-08cb-4b26-82db-87ccf08b5805.png)

**Comment by jerdbaer** [comment]
![STANDARD ELEMENTS](https://user-images.githubusercontent.com/84909173/158697055-2ba12d8e-c405-4d73-99de-212dad5869b3.png)
![COLORS](https://user-images.githubusercontent.com/84909173/158697073-9466fd70-5621-450b-8446-b667f0de4f1f.png)
![BUTTONS](https://user-images.githubusercontent.com/84909173/158697081-6e986f62-e287-4b80-ad1a-278103601dab.png)
![FORM-ELEMENTS](https://user-images.githubusercontent.com/84909173/158697233-e9d2265d-14ca-4cf6-afe0-7157cb3c5aff.png)

**Comment by jerdbaer** [comment]
<img width="210" alt="image" src="https://user-images.githubusercontent.com/84909173/158697772-ef032c0e-c6da-4a67-9f01-52e855f31bd6.png">
